server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order:8081
          predicates:
            - Path=/api/v1/orders/**

        - id: event-service
          uri: http://event:8082
          predicates:
            - Path=/api/v1/events/**

        - id: notification-service
          uri: http://notification:8083
          predicates:
            - Path=/api/v1/notifications/**

        - id: analytics-service
          uri: http://analytics:8084
          predicates:
            - Path=/api/v1/analytics/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG