spring:
  application:
    name: analytics-service

  data:
    mongodb:
      uri: mongodb://analytics-mongo:27017/analyticsdb

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8084
  address: 0.0.0.0

logging:
  level:
    root: INFO
    com.ecommerce.analytics: DEBUG